
=======
# CI environment
dist: bionic

jobs:
  include:
    - language: node_js
      node_js: 16
      python: "3.8.10"
      install:
        - source django-env/bin/activate
        - cd fitvoxbackend
        - pip install -r requirements.txt
        - pip install coveralls
        - cd ../fitvoxfrontend
        - yarn install
        - yarn global add coveralls
        - gem install coveralls-lcov
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coerage/lcov.info > coverage.json
        - cd ../fitboxbackend
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - sonar-scanner
        - coveralls --merge=../fitvoxfrontend/coverage.json